package models;

/*
 * From http://www.azlyrics.com/j/jackson.html
 * */

public class Texts {
	public static String[][] list=
		{
			{
				"Keep The Faith",
				"If You Call Out Loud",
				"Will It Get Inside",
				"Through The Heart Of Your Surrender",
				"To Your Alibis",
				"And You Can Say The Words",
				"Like You Understand",
				"But The Power's In Believing",
				"So Give Yourself A Chance",
				"'Cause You Can",
				"Climb The Highest Mountain",
				"Swim The Deepest Sea, Hee",
				"All You Need Is The Will To Want It",
				"And Uhh, Little Self-Esteem",
				"So Keep The Faith",
				"Don't Let Nobody Turn You 'Round",
				"You Gotta Know When It's Good To Go",
				"To Get Your Dreams Up Off The Ground",
				"Keep The Faith, Baby, Yea",
				"Because It's Just",
				"A Matter Of Time",
				"Before Your Confidence Will Win Out",
				"Believe In Yourself",
				"No Matter What It's Gon' Take",
				"You Can Be A Winner",
				"But You Got To Keep The Faith",
				"...Gon' Keep It Brother",
				"You Got It",
				"And When You Think Of Trust",
				"Does It Lead You Home",
				"To A Place That You Only Dream Of",
				"When You're All Alone",
				"And You Can Go By Feel",
				"'Stead Of Circumstance",
				"But The Power's In Beliving",
				"So Give Yourself A Chance",
				"I Know That You Can Sail Across The Water",
				"Float Across The Sky, High",
				"Any Road That You Take",
				"Will Get You There",
				"If You Only Try",
				"So Keep The Faith, Ow",
				"Don't Let Nobody Take You Down,Brother",
				"Just Keep Your Eyes On The Prize",
				"And Your Feet Flat On The Ground",
				"Keep The Faith, Baby, Yea",
				"Because It's Just A Matter Of Time",
				"Before Your Confidence Will Win Out",
				"I Told My Brother How To Do The Thing Right",
				"Lift Up Your Head And Show The World You Got Pride",
				"Go For What You Want",
				"Don't Let 'Em Get In Your Way",
				"You Can Be A Winner",
				"But You Got To Keep The Faith",
				"Gon' Keep It Brother",
				"You Got It",
				"I Know That Keepin' The Faith",
				"Means Never Givin' Up On Love",
				"But The Power That Love Has To Make It Right",
				"Makes It Makes It Right",
				"Keep The Faith",
				"Don't Let Nobody Turn You 'Round Brother",
				"You Got To KnowWhen It's Good To Go",
				"To Get Your Dreams Up Off The Ground",
				"Keep The Faith Baby, Yea",
				"Because It's Just A Matter Of Time",
				"Before Your Confidence Will Win Out",
				"Better Stand Up And Act Like You Wanna Do Right",
				"Don't Play The Fool For The Rest Of Your Life",
				"Work On It Brother And You'll Make It Someday",
				"Go For What You Want",
				"And Don't Forget The Faith",
				"Look At Yourself",
				"And What You Doin' Right Now",
				"Stand Back A Minute",
				"Just To Check Yourself Out",
				"Straighten Out Your Life",
				"And How You're Livin' Each Day",
				"Get Yourself Together",
				"'Cause You Got To Keep The Faith",
				"Uh, Uh, Uh",
				"Don't Let Nobody Take You Down, Brother",
				"Just Keep Your Eyes On The Prize",
				"And Your Feet Flat On The Ground",
				"Keep The Faith, Baby, Yea",
				"Because It's Just A Matter Of Time",
				"Before Your Confidence Will Win Out",
				"Lift Up Your Mind",
				"Before Your Mind Gets Blown",
				"Some Things In Life",
				"You Best Just Leave Them Alone",
				"Go For What You Want",
				"Don't Let It Get In Your Way",
				"You Can Make It Happen",
				"But Ya Got Ta Keep The Faith",
				"Gon' Keep It Brother",
				"You Got To Keep The Faith",
				"Yeah Keep The Faith",
				"Gon' Keep It Sister",
				"You Got To Keep The Faith",
				"Now, Now",
				"I'll Show My Brotha",
				"How To Do The Thing Right",
				"Lift Up Your Head",
				"And Show The World You Got Pride",
				"Go For What You Want",
				"Don't Let 'Em Get In Your Way",
				"You Can Be A Winner",
				"If You Keep The Faith",
				"Straighten Out Yourself",
				"And Get Your Mind On Track",
				"Dust Off Your Butt",
				"And Get Your Self-Respect Back",
				"You've Known Me Long Enough",
				"To Know That I Don't Play",
				"Take It Like You Want It",
				"But You Got To Keep The Faith Gon'",
				"Don't Let Nobody Take You Down",
				"Just Keep Your Eyes On The Prize",
				"And Get Your Feet Back On The Ground",
				"Keep The Faith, Baby, Yea",
				"Because It's Just A Matter Of Time",
				"Before Your Confidence Will Win Out",
				"But Till That Day I Said You've Got To Keep The Faith!",
			},
			{
				"Smile",
				"Smile, though your heart is aching",
				"Smile, even though it's breaking",
				"When there are clouds in the sky",
				"You'll get by...",
				"If you smile",
				"With your fear and sorrow",
				"Smile and maybe tomorrow",
				"You'll find that life is still worthwhile",
				"If you just...",
				"Light up your face with gladness",
				"Hide every trace of sadness",
				"Although a tear may be ever so near",
				"That's the time you must keep on trying",
				"Smile, what's the use of crying",
				"You'll find that life is still worthwhile",
				"If you just...",
				"Smile, though your heart is aching",
				"Smile, even though it's breaking",
				"When there are clouds in the sky",
				"You'll get by...",
				"If you smile",
				"Through your fear and sorrow",
				"Smile and maybe tomorrow",
				"You'll find that life is still worthwhile",
				"If you just smile...",
				"That's the time you must keep on trying",
				"Smile, what's the use of crying",
				"You'll find that life is still worthwhile",
				"If you just smile",				
			},
			{
				
				"Heal The World",
				"There's A Place In",
				"Your Heart",
				"And I Know That It Is Love",
				"And This Place Could",
				"Be Much",
				"Brighter Than Tomorrow",
				"And If You Really Try",
				"You'll Find There's No Need",
				"To Cry",
				"In This Place You'll Feel",
				"There's No Hurt Or Sorrow",
				"There Are Ways",
				"To Get There",
				"If You Care Enough",
				"For The Living",
				"Make A Little Space",
				"Make A Better Place...",
				"Heal The World",
				"Make It A Better Place",
				"For You And For Me",
				"And The Entire Human Race",
				"There Are People Dying",
				"If You Care Enough",
				"For The Living",
				"Make A Better Place",
				"For You And For Me",
				"If You Want To Know Why",
				"There's A Love That",
				"Cannot Lie",
				"Love Is Strong",
				"It Only Cares For",
				"Joyful Giving",
				"If We Try",
				"We Shall See",
				"In This Bliss",
				"We Cannot Feel",
				"Fear Or Dread",
				"We Stop Existing And",
				"Start Living",
				"Then It Feels That Always",
				"Love's Enough For",
				"Us Growing",
				"So Make A Better World",
				"Make A Better World...",
				"Heal The World",
				"Make It A Better Place",
				"For You And For Me",
				"And The Entire Human Race",
				"There Are People Dying",
				"If You Care Enough",
				"For The Living",
				"Make A Better Place",
				"For You And For Me",
				"And The Dream We Were",
				"Conceived In",
				"Will Reveal A Joyful Face",
				"And The World We",
				"Once Believed In",
				"Will Shine Again In Grace",
				"Then Why Do We Keep",
				"Strangling Life",
				"Wound This Earth",
				"Crucify Its Soul",
				"Though It's Plain To See",
				"This World Is Heavenly",
				"Be God's Glow",
				"We Could Fly So High",
				"Let Our Spirits Never Die",
				"In My Heart",
				"I Feel You Are All",
				"My Brothers",
				"Create A World With",
				"No Fear",
				"Together We'll Cry",
				"Happy Tears",
				"See The Nations Turn",
				"Their Swords",
				"Into Plowshares",
				"We Could Really Get There",
				"If You Cared Enough",
				"For The Living",
				"Make A Little Space",
				"To Make A Better Place...",
				"Heal The World",
				"Make It A Better Place",
				"For You And For Me",
				"And The Entire Human Race",
				"There Are People Dying",
				"If You Care Enough",
				"For The Living",
				"Make A Better Place",
				"For You And For Me",
				"Heal The World",
				"Make It A Better Place",
				"For You And For Me",
				"And The Entire Human Race",
				"There Are People Dying",
				"If You Care Enough",
				"For The Living",
				"Make A Better Place",
				"For You And For Me",
				"Heal The World",
				"Make It A Better Place",
				"For You And For Me",
				"And The Entire Human Race",
				"There Are People Dying",
				"If You Care Enough",
				"For The Living",
				"Make A Better Place",
				"For You And For Me",
				"There Are People Dying",
				"If You Care Enough",
				"For The Living",
				"Make A Better Place",
				"For You And For Me",
				"There Are People Dying",
				"If You Care Enough",
				"For The Living",
				"Make A Better Place",
				"For You And For Me",
				"You And For Me",
				"You And For Me",
				"Heal the world we live in, save it for our children",
				"Heal the world we live in, save it for our children",
				
			}
		};
	
	
}
